defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5

development:
  <<: *defaults
  database: manga_bytes_development
  username: manga_bytes
  
  password:

test:
  <<: *defaults
  database: manga_bytes_test
  username: manga_bytes
  password:
